pipeline:
  identifier: Build_jhttp_1742289362143
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1742223495982
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - type: Run
                identifier: build_java_app
                name: Build Java App
                spec:
                  shell: Sh
                  command: |-
                    echo "Welcome to Harness CI"
                    mvn -B package --file pom.xml
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: gke
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Ignore
        delegateSelectors:
          - kubernetes-delegate
