pipeline:
  identifier: Build_jhttp_1742210836704
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Shirad_Gith
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
        delegateSelectors:
          - kubernetes-delegate
